export type Employee = {
    id: string;
    employeeId: string;
    name: string;
    academicTitle?: string | null;
    preferredName?: string | null;
    email: string;
    phone: string;
    alternatePhone?: string | null;
    gender: "Laki-Laki" | "Perempuan";
    employmentType: "PERMANENT" | "CONTRACT" | "PROBATION" | "INTERN";
    departmentId: string;
    divisionId?: string | null;
    positionId: string;
    managerId?: string | null;
    faceDescriptor?: number[];
    joinDate: string;
    employmentStartDate?: string | null;
    employmentEndDate?: string | null;
    probationEndDate?: string | null;
    totalLeave: number;
    usedLeave: number;
    avatarUrl?: string | null;
    isActive: boolean;
    statusChangedAt?: string | null;
    shiftId?: string | null;
    bypassLocation: boolean;
    basicSalary: number;
    locations?: { id: string; name: string }[];
    /** Persisted payroll components (from DB) OR input DTOs (from API) */
    payrollComponents?: (EmployeePayrollComponent | PayrollComponentInput)[];
    /** Relasi Prisma — tersedia jika di-include dalam query */
    manager?: { id: string; name: string; employeeId: string };
    subordinates?: { id: string; name: string; employeeId: string }[];
    departmentRel?: { id: string; name: string } | null;
    divisionRel?: { id: string; name: string } | null;
    positionRel?: { id: string; name: string } | null;
    levelRel?: { id: string; name: string } | null;
    statusHistories?: EmployeeStatusHistory[];
    birthPlace?: string | null;
    birthDate?: string | null;
    maritalStatus?: string | null;
    bloodType?: string | null;
    religion?: string | null;
    lastEducation?: string | null;
    notes?: string | null;
    nationalId?: string | null;
    familyCardNumber?: string | null;
    bpjsEmploymentNumber?: string | null;
    bpjsHealthNumber?: string | null;
    idCardAddress?: string | null;
    domicileAddress?: string | null;
    emergencyContactName?: string | null;
    emergencyContactRelationship?: string | null;
    emergencyContactPhone?: string | null;
    bankName?: string | null;
    bankAccountNumber?: string | null;
    bankAccountHolderName?: string | null;
    ptkpStatus?: string | null;
    ptkpEffectiveDate?: string | null;
};

export type EmployeeStatusHistory = {
    id: string;
    employeeId: string;
    wasActive: boolean;
    isActive: boolean;
    reason: string;
    effectiveDate: string;
    changedByUserId?: string | null;
    changedByIdentifier: string;
    changedByName?: string | null;
    changedByRole?: string | null;
    createdAt: string;
    actor?: { username: string; displayName: string } | null;
};

export type EmployeePayrollComponent = {
    id: string;
    employeeId: string;
    componentId: string;
    amount: number;
    component?: {
        id: string;
        name: string;
        type: "earning" | "deduction";
    };
};

/**
 * Input shape for creating/updating payroll components.
 * Does NOT have id/employeeId — those are generated by the DB.
 */
export type PayrollComponentInput = {
    componentId: string;
    amount: number;
};

export type AttendanceRecord = {
    id: string;
    employeeId: string;
    date: string;
    clockIn?: string | null;
    clockOut?: string | null;
    clockInLocation?: { lat: number; lng: number } | null;
    clockOutLocation?: { lat: number; lng: number } | null;
    clockInPhoto?: string | null;
    clockOutPhoto?: string | null;
    status: "present" | "late" | "absent" | "leave";
    notes?: string | null;
};

export type PayslipItem = {
    id?: string;
    type: "ALLOWANCE" | "DEDUCTION";
    name: string;
    amount: number;
};

export type PayslipRecord = {
    id: string;
    employeeId: string;
    period: string;
    basicSalary: number;
    items: PayslipItem[];
    overtime: number;
    netSalary: number;
    issuedDate: string;
    notes?: string | null;
};

export type AttendanceCorrection = {
    id: string;
    employeeId: string;
    targetDate: string;
    proposedClockIn?: string | null;
    proposedClockOut?: string | null;
    reason: string;
    attachmentUrl?: string | null;
    status: "PENDING" | "APPROVED" | "REJECTED";
    assignedManagerId?: string | null;
    createdAt: string;
    updatedAt: string;
};

export type WorkShiftDay = {
    id: string;
    shiftId: string;
    dayOfWeek: number; // 0=Sunday, 1=Monday, ... 6=Saturday
    startTime: string;
    endTime: string;
    isOff: boolean;
};

export type WorkShift = {
    id: string;
    name: string;
    isDefault: boolean;
    lateCheckIn: number;
    earlyCheckIn: number;
    lateCheckOut: number;
    earlyCheckOut: number;
    days: WorkShiftDay[];
};

export type LeaveRequest = {
    id: string;
    employeeId: string;
    type: "annual" | "sick" | "personal" | "maternity" | "paternity";
    startDate: string;
    endDate: string;
    reason: string;
    status: "pending" | "approved" | "rejected";
    attachment?: string | null;
    createdAt: string;
};

export type NewsItem = {
    id: string;
    title: string;
    content: string;
    category: "announcement" | "event" | "policy" | "general";
    author: string;
    createdAt: string;
    isPinned: boolean;
    mediaUrl?: string | null;
    mediaName?: string | null;
};

export type TodoItem = {
    id: string;
    employeeId: string;
    text: string;
    completed: boolean;
    createdAt: string;
};

export type VisitStatus = "draft" | "clocked_in" | "clocked_out";

export type VisitPhotoPhase = "CLOCK_IN" | "CLOCK_OUT";

export type VisitPhotoCategory =
    | "LOKASI"
    | "AKTIVITAS"
    | "HASIL"
    | "DOKUMEN"
    | "LAINNYA";

/** Payload foto sebelum divalidasi dan diproses ulang oleh server. */
export type VisitPhotoDraft = {
    dataUrl: string;
    capturedAtDevice: string;
    category: VisitPhotoCategory;
    caption?: string | null;
};

/** Metadata bukti foto yang aman dikirim ke UI; storage path tidak diekspos. */
export type VisitPhoto = {
    id: string;
    phase: VisitPhotoPhase;
    sequence: number;
    category: VisitPhotoCategory;
    caption?: string | null;
    capturedAtDevice?: string | null;
    receivedAtServer: string;
    officialTimestamp: string;
    latitude: number;
    longitude: number;
    accuracyMeters?: number | null;
    distanceToTargetMeters?: number | null;
    sha256Original: string;
    mimeType: string;
    fileSize: number;
    width: number;
    height: number;
    overlayVersion: number;
    stampedUrl: string;
    originalUrl: string;
};

export type VisitReport = {
    id: string;
    employeeId: string;
    employeeName?: string | null;
    employeeDepartment?: string | null;
    date: string;
    clockInTime?: string | null;
    clockOutTime?: string | null;
    clientName: string;
    clientAddress: string;
    purpose: string;
    result?: string | null;
    visitLocation?: { lat: number; lng: number } | null;
    visitRadius: number;
    clockInLocation?: { lat: number; lng: number } | null;
    clockOutLocation?: { lat: number; lng: number } | null;
    clockInPhotos?: string[] | null;
    clockOutPhotos?: string[] | null;
    photos?: VisitPhoto[];
    status: VisitStatus;
    hrChecked: boolean;
    notes?: string | null;
    createdAt: string;
};

export type OvertimeRequest = {
    id: string;
    employeeId: string;
    date: string;
    startTime: string;
    endTime: string;
    hours: number;
    approvedHours?: number | null;
    isHoliday: boolean;
    overtimePay: number;
    reason: string;
    status: "pending" | "approved" | "rejected";
    createdAt: string;
};
